"""Deterministic logical-work identity and pure orchestration policy.

WO38-A separates immutable scientific work from mutable execution attempts.  This
package exposes only data contracts and pure planning/reduction functions; worker,
queue, lease, transport, persistence, and execution backends belong to later cards.
"""

from .models import (
    EXPERIMENT_WORK_PLAN_SCHEMA_ID,
    LOGICAL_WORK_CELL_SCHEMA_ID,
    LOGICAL_WORK_UNIT_SCHEMA_ID,
    ORCHESTRATION_MODEL_SCHEMA_VERSION,
    WORK_ATTEMPT_IDENTITY_SCHEMA_ID,
    WORK_ATTEMPT_SCHEMA_ID,
    DigestReferenceV1,
    ExperimentWorkPlanV1,
    LogicalWorkCellV1,
    LogicalWorkUnit,
    WorkAttempt,
    WorkAttemptOutcomeV1,
    WorkKindV1,
)
from .planner import (
    ATTEMPT_RESULT_RESOLUTION_SCHEMA_ID,
    COORDINATOR_RESPONSIBILITY_CONTRACT_SCHEMA_ID,
    COORDINATOR_RESPONSIBILITY_CONTRACT_V1,
    COORDINATOR_RESPONSIBILITY_SEQUENCE_V1,
    ORCHESTRATION_PLANNER_SCHEMA_VERSION,
    AttemptResultResolutionStatusV1,
    AttemptResultResolutionV1,
    CoordinatorResponsibilityContractV1,
    CoordinatorResponsibilityV1,
    build_experiment_work_plan,
    canonical_aggregation_order,
    order_logical_work_units_for_aggregation,
    resolve_successful_attempts,
    snapshot_logical_cells,
)
from .seeds import (
    MAX_ORCHESTRATION_SEED,
    ORCHESTRATION_CELL_SEED_DOMAIN_V1,
    ORCHESTRATION_MASTER_SEED_IDENTITY_DOMAIN_V1,
    ORCHESTRATION_SEED_DERIVATION_DOMAIN_V1,
    ORCHESTRATION_SEED_POLICY_VERSION_V1,
    ORCHESTRATION_SEED_SCHEMA_VERSION,
    MasterSeedIdentityV1,
    SeedDerivationCollisionError,
    SeedDerivationV1,
    StableCellIdentityV1,
    build_master_seed_identity,
    derive_logical_cell_seed,
    derive_logical_cell_seed_batch,
)


__all__ = [
    "ATTEMPT_RESULT_RESOLUTION_SCHEMA_ID",
    "COORDINATOR_RESPONSIBILITY_CONTRACT_SCHEMA_ID",
    "COORDINATOR_RESPONSIBILITY_CONTRACT_V1",
    "COORDINATOR_RESPONSIBILITY_SEQUENCE_V1",
    "EXPERIMENT_WORK_PLAN_SCHEMA_ID",
    "LOGICAL_WORK_CELL_SCHEMA_ID",
    "LOGICAL_WORK_UNIT_SCHEMA_ID",
    "MAX_ORCHESTRATION_SEED",
    "ORCHESTRATION_CELL_SEED_DOMAIN_V1",
    "ORCHESTRATION_MASTER_SEED_IDENTITY_DOMAIN_V1",
    "ORCHESTRATION_MODEL_SCHEMA_VERSION",
    "ORCHESTRATION_PLANNER_SCHEMA_VERSION",
    "ORCHESTRATION_SEED_DERIVATION_DOMAIN_V1",
    "ORCHESTRATION_SEED_POLICY_VERSION_V1",
    "ORCHESTRATION_SEED_SCHEMA_VERSION",
    "WORK_ATTEMPT_IDENTITY_SCHEMA_ID",
    "WORK_ATTEMPT_SCHEMA_ID",
    "AttemptResultResolutionStatusV1",
    "AttemptResultResolutionV1",
    "CoordinatorResponsibilityContractV1",
    "CoordinatorResponsibilityV1",
    "DigestReferenceV1",
    "ExperimentWorkPlanV1",
    "LogicalWorkCellV1",
    "LogicalWorkUnit",
    "MasterSeedIdentityV1",
    "SeedDerivationCollisionError",
    "SeedDerivationV1",
    "StableCellIdentityV1",
    "WorkAttempt",
    "WorkAttemptOutcomeV1",
    "WorkKindV1",
    "build_experiment_work_plan",
    "build_master_seed_identity",
    "canonical_aggregation_order",
    "derive_logical_cell_seed",
    "derive_logical_cell_seed_batch",
    "order_logical_work_units_for_aggregation",
    "resolve_successful_attempts",
    "snapshot_logical_cells",
]
