"""Source-linked causal replay microscope contracts."""

from .fixtures import complete_trace_fixture, incomplete_legacy_trace_fixture
from .index import TraceIndexVerification, build_trace_index, verify_trace_index
from .lineage import build_player_action_trace
from .models import (
    MECHANISTIC_INTERPRETATION,
    TRACE_EDGE_ORDER,
    TRACE_INDEX_SCHEMA_ID,
    TRACE_INDEX_SCHEMA_VERSION,
    TRACE_SOURCE_SCHEMA_ID,
    TRACE_SOURCE_SCHEMA_VERSION,
    TRACE_STAGE_ORDER,
    MechanisticTraceIndex,
    PlayerActionTrace,
    RecordedTraceEvent,
    TraceArtifactKind,
    TraceAvailability,
    TraceEdge,
    TraceEdgeKind,
    TraceLinkStatus,
    TraceNode,
    TraceProvenance,
    TraceSourceRecording,
    TraceStage,
    TraceUnavailableReason,
)

__all__ = [
    "MECHANISTIC_INTERPRETATION",
    "TRACE_EDGE_ORDER",
    "TRACE_INDEX_SCHEMA_ID",
    "TRACE_INDEX_SCHEMA_VERSION",
    "TRACE_SOURCE_SCHEMA_ID",
    "TRACE_SOURCE_SCHEMA_VERSION",
    "TRACE_STAGE_ORDER",
    "MechanisticTraceIndex",
    "PlayerActionTrace",
    "RecordedTraceEvent",
    "TraceArtifactKind",
    "TraceAvailability",
    "TraceEdge",
    "TraceEdgeKind",
    "TraceIndexVerification",
    "TraceLinkStatus",
    "TraceNode",
    "TraceProvenance",
    "TraceSourceRecording",
    "TraceStage",
    "TraceUnavailableReason",
    "build_player_action_trace",
    "build_trace_index",
    "complete_trace_fixture",
    "incomplete_legacy_trace_fixture",
    "verify_trace_index",
]
