"""Canonical, data-only portable pack contracts.

This WO39-A surface defines logical identity and byte-format declarations only.
Untrusted archive validation, staging, installation, and domain-specific builders
are deliberately introduced by later work orders.
"""

from .formats import (
    K2PACK_CANONICALIZATION_ID,
    K2PACK_CANONICALIZATION_VERSION,
    K2PACK_MANIFEST_PATH,
    K2PACK_ZIP_COMPRESSLEVEL,
    K2PACK_ZIP_COMPRESSION,
    K2PACK_ZIP_TIMESTAMP,
    canonical_json_bytes,
    canonical_manifest_bytes,
    canonical_toml_bytes,
    inspect_payload_format_claim,
    load_canonical_json_bytes,
    load_canonical_toml_bytes,
    load_manifest_bytes,
    normalized_archive_paths,
    normalized_zip_info,
    require_semver,
    require_semver_range,
)
from .identity import (
    CREATOR_ID_ALGORITHM,
    PACK_IDENTITY_ALGORITHM,
    PACK_IDENTITY_PROJECTION_SCHEMA_ID,
    PACK_IDENTITY_PROJECTION_SCHEMA_VERSION,
    TRANSPORT_IDENTITY_ALGORITHM,
    PackPayloadIdentityVerificationV1,
    UnverifiedPackTransportIdentityV1,
    canonical_creator_metadata_bytes,
    canonical_pack_identity_bytes,
    derive_creator_id,
    derive_pack_id,
    describe_archive_transport,
    inventory_sha256,
    pack_identity_projection,
    transport_sha256,
    verify_pack_id,
    verify_pack_payload_identity,
)
from .models import (
    PACK_FORMAT_ID,
    PACK_FORMAT_VERSION,
    PACK_MANIFEST_SCHEMA_ID,
    PACK_MANIFEST_SCHEMA_VERSION,
    PackCompatibilityLevelV1,
    PackCompatibilityV1,
    PackContentFormatV1,
    PackContentModeV1,
    PackCreatorV1,
    PackDependencyV1,
    PackEntrypointV1,
    PackFileV1,
    PackLicenseV1,
    PackManifestV1,
    PackProvenanceV1,
    PackRedistributionPolicyV1,
    PackRegistryKeyV1,
    PackSchemaRequirementV1,
    PackTypeV1,
    PackVersionRequirementV1,
)


__all__ = [
    "CREATOR_ID_ALGORITHM",
    "K2PACK_CANONICALIZATION_ID",
    "K2PACK_CANONICALIZATION_VERSION",
    "K2PACK_MANIFEST_PATH",
    "K2PACK_ZIP_COMPRESSLEVEL",
    "K2PACK_ZIP_COMPRESSION",
    "K2PACK_ZIP_TIMESTAMP",
    "PACK_FORMAT_ID",
    "PACK_FORMAT_VERSION",
    "PACK_IDENTITY_ALGORITHM",
    "PACK_IDENTITY_PROJECTION_SCHEMA_ID",
    "PACK_IDENTITY_PROJECTION_SCHEMA_VERSION",
    "PACK_MANIFEST_SCHEMA_ID",
    "PACK_MANIFEST_SCHEMA_VERSION",
    "TRANSPORT_IDENTITY_ALGORITHM",
    "PackCompatibilityLevelV1",
    "PackCompatibilityV1",
    "PackContentFormatV1",
    "PackContentModeV1",
    "PackCreatorV1",
    "PackDependencyV1",
    "PackEntrypointV1",
    "PackFileV1",
    "PackLicenseV1",
    "PackManifestV1",
    "PackPayloadIdentityVerificationV1",
    "PackProvenanceV1",
    "PackRedistributionPolicyV1",
    "PackRegistryKeyV1",
    "PackSchemaRequirementV1",
    "PackTypeV1",
    "PackVersionRequirementV1",
    "UnverifiedPackTransportIdentityV1",
    "canonical_creator_metadata_bytes",
    "canonical_json_bytes",
    "canonical_manifest_bytes",
    "canonical_pack_identity_bytes",
    "canonical_toml_bytes",
    "derive_creator_id",
    "derive_pack_id",
    "describe_archive_transport",
    "inspect_payload_format_claim",
    "inventory_sha256",
    "load_canonical_json_bytes",
    "load_canonical_toml_bytes",
    "load_manifest_bytes",
    "normalized_archive_paths",
    "normalized_zip_info",
    "pack_identity_projection",
    "require_semver",
    "require_semver_range",
    "transport_sha256",
    "verify_pack_id",
    "verify_pack_payload_identity",
]
